name: 自动采集

# 触发条件
on:
  # push的时候触发
  # push:
  #   branches: main
  workflow_dispatch:
  # 定时触发
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    # 此处是UTC时间 即北京时间 -8小时
    - cron: '40 2,12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.7'
    - name: 加载缓存  
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r requirements.txt
    - name: 执行任务1
      run: |
        python main1.py
    - name: 执行任务2
      run: |
        python main2.py
    - name: 执行任务3
      run: |
        python main3.py
    - name: 执行任务4
      run: |
        python main4.py
    - name: 执行任务5
      run: |
        python main5.py
    - name: 执行任务6
      run: |
        python main6.py
    - name: 执行任务7
      run: |
        python main7.py
    - name: 执行任务8
      run: |
        python main8.py
    - name: 执行任务9
      run: |
        python main9.py 
    - name: 提交更改
      run: |                 
         git config --local user.email "hermanbrayden001@gmail.com"
         git config --local user.name "hermanb001"
         git add subscribe/origamiboy
         git add subscribe/hellopool
         git add subscribe/sspool
         git add subscribe/kingfu
         git add subscribe/guobang
         git add subscribe/guest997
         git add subscribe/eu-proxypool
         git add subscribe/ednovas
         git add subscribe/clash.yml         
         git commit -m "更新订阅链接"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         # github_token: ${{ secrets.TOKEN }}
         branch: main
